import { it, expect } from "vitest";
import { TemporalVisibility } from "../src/rendering/visibility/TemporalVisibility";
import { RenderWorld } from "../src/rendering/RenderWorld";
import { Camera } from "../src/rendering/Camera";
it("only reuses exact stable snapshots and warms new objects conservatively", () => {
  const w = new RenderWorld(4),
    c = new Camera(),
    t = new TemporalVisibility(w);
  w.count = 1;
  w.entityId[0] = 3;
  c.update(1);
  const step = (revision = 0, width = 100) =>
    t.prepare(w, c, revision, width, 100, false);
  t.enabled = true;
  step();
  expect(t.newObjects).toBe(true);
  expect(t.reuse).toBe(false);
  step();
  expect(t.reuse).toBe(false);
  step();
  expect(t.reuse).toBe(true);
  c.setPosition(40, 2, 5);
  c.update(1);
  step();
  expect(t.reuse).toBe(false);
  step();
  expect(t.reuse).toBe(true);
  c.setTarget(-20, 0, 0);
  c.update(1);
  step();
  expect(t.reuse).toBe(false);
  step(0, 200);
  expect(t.resetReason).toBe("projection");
  w.matrices[12] = 100;
  step(0, 200);
  expect(t.resetReason).toBe("motion");
  w.jointCount = 1;
  w.jointMatrices[12] = 2;
  step();
  expect(t.resetReason).toBe("deformation");
  w.morphWeightCount = 1;
  w.morphWeights[0] = 0.5;
  step();
  expect(t.reuse).toBe(false);
  step(1);
  expect(t.resetReason).toBe("material");
  w.entityId[0] = 4;
  step(1);
  expect(t.newObjects).toBe(true);
  expect(t.reuse).toBe(false);
  step(1);
  expect(t.reuse).toBe(false);
  step(1);
  expect(t.reuse).toBe(true);
  t.enabled = false;
  step();
  t.enabled = true;
  step();
  expect(t.newObjects).toBe(true);
});
